image:
  file: .gitpod.Dockerfile

ports:
    - port: 3000
      onOpen: ignore

vscode:
  extensions:
    - learn-pack.learnpack-vscode
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
    
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
        # enable for pull requests coming from this repo (defaults to true)
        pullRequests: false
        # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
        addComment: false

# This will make it so that on workspace start it will run a file called `app.py`
tasks:
  - command: python3 main.py